### ISSUE TITLE
Vendor-Specific Video code modified

### ISSUE THREAD

**Issue by zolive59** [balu100/dolby-vision-for-windows#1]
Hello, thank you for this information !
How did you know which digit to modify in the VSVDB ?
I read this on a forum:
"Dolby Vision information is held in a 12 or 15 byte VSVDB (Vendor Specific Video Data Block - more commonly know as VSDB) within the CEA Extension of the EDID - you can identify it from Dolby's IEE Registration Code - 00D046 - but it needs decoding - VSDB formats are generally not public domain, and are most certainly not in Dolby's case."
My TV is a Sony Bravia, so the code is different from LG.
THANKS !

**Comment by balu100** [comment]
Can you please share the payload (hex string) from your vendor specific video (1 through 9 step)

**Comment by zolive59** [comment]
Thank !
vendor specific video payload (hex string)
4403609248458f

**Comment by djnice** [comment]
Dolby VSVDB Calc: https://discourse.coreelec.org/uploads/short-url/uJlVOw1StIgxqJnJyKuGwlC57vQ.xlsm

**Comment by djnice** [comment]
> Thank ! vendor specific video payload (hex string) 4403609248458f

Your TV only support LLDV, so the nem payload for LLDV + LLDV-HDMI is:
4403619248458f

**Comment by balu100** [comment]
Thanks for helping us out. It is highly appreciated.
The XLSM file has been added to the main README with appropriate thanks.


Dolby VSVDB Calc: https://discourse.coreelec.org/uploads/short-url/uJlVOw1StIgxqJnJyKuGwlC57vQ.xlsm
4403619248458f
