### ISSUE TITLE
No UHD resolution to select on C2

### ISSUE THREAD

**Issue by holingher** [balu100/dolby-vision-for-windows#10]
I have a 4080S (565.90) + LG C2 and I tried to follow your instructions. After I executed restart64.exe the TV went to some basic configuration like 1080p, 8 bit, 60 Hz, no HDR (not even the option to enable it). The display name is still there: LG TV SSCR2. Can you provide me a backup from yours if you have a C2? Tried to go back to my backup but it did not work. Is there a way to roll back? Tried to DDU and reinstall, another hdmi port on LG, but nothing seems to work. Thanks

**Comment by balu100** [comment]
While the name is the same, I have a C1, so just run the "reset-all.exe" from the CRU to reset everything.
