### ISSUE TITLE
Vendor-Specific Video section missing - Vivobook 15 OLED (X1505)

### ISSUE THREAD

**Issue by tkachevaa** [balu100/dolby-vision-for-windows#6]
I can't find Vendor-Specific Video section in aw edid editor version 3_0_20.
In Vendor and Product ID section there is no hex string.

**Comment by balu100** [comment]
Did you export a compatible monitor/TV?

This is how an unsupported one looks:
![image](https://github.com/user-attachments/assets/8967487a-cf99-47ce-ac3a-1db6a6d9b5c3)

This is how a supported one looks:
![image](https://github.com/user-attachments/assets/1349fc80-d2da-437e-952e-a597a332a0af)

**Comment by balu100** [comment]
Does your CRU have extension block(s)?

Here is an example of a configuration that works:
![Working Example](https://github.com/user-attachments/assets/28cd795c-1ff1-4541-a351-55d49189ed64)

And here is an example of one that does not work:
![Non-working Example](https://github.com/user-attachments/assets/e2196430-a7d5-4d2c-9b43-bac6560767d3)

**Comment by tkachevaa** [comment]
What i have: CTA-861: 0 detailed resolutions, 2 data blocks.
Colorimetry 2 bytes and HDR static metadata 7 bytes

**Comment by tkachevaa** [comment]
I was not sure. Thanks for help.
